-- require("lazy").setup("plugins")
require('usr.packages')
require("usr.keymaps")
require("usr.options")
require('usr.telescope')
require('usr.treesitter')
require('usr.lsp')
require('usr.nvim-cmp')
require("usr.lualine")
require("usr.tabline")
require('usr.autosession')
-- require('usr.dashboard')
-- require('usr.autocommands')
-- require('usr.nvim-tree')
-- require('usr.leap')
-- require('usr.autopairs')
-- require('usr.prettyfold')
-- require('usr.dap')
