vim.o.guicursor = "n-v-ve-o-r-sm:hor100,i:ver100,a:blinkwait1-blinkoff10-blinkon50"
vim.cmd("colorscheme vim-monokai-tasty")
require("user.keybindings")
require("user.options")
require("user.plugins")
require("user.telescope")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.tree")
require("user.bufferline")
require("user.toggleterm")
require("user.lualine")
require("user.indentline")
require("user.whichkey")
require("user.illuminate")
require("user.dap")
require("user.autocommands")
require("user.alpha")
require("user.project")
require("user.impatient")
require("user.window")
require("user.coderunner")
require("user.colorizer")
